resources:
  - name: concourse-examples
    type: git
    icon: github
    source:
      uri: https://github.com/zak-02/s3.git

  - name: produce-chart
    type: git
    icon: githubccc
    source:
      uri: https://github.com/zak-02/submodule.git

jobs:
  - name: chart-and-upload
    plan:
      - get: produce-chart
      - get: concourse-examples
      - task: build-and-upload
        params:
          AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
          inputs:
            - name: produce-chart
            - name: concourse-examples
          run:
            path: sh
            args:
              - -c
              - |
                cd produce-chart
                pip install pandas matplotlib boto3
                python netflix.py
                cp chart.png ../concourse-examples/
                cd ../concourse-examples
                python upload.py
